version: "3"

services:
  bot:
    container_name: bot
    image: discord/bot:latest
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:secret@db:5432/default
    volumes:
      - .:/app:cached
    depends_on:
      - db
      - g4f
    command: python -m bot

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: default
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always

  g4f:
    container_name: g4f
    image: hlohaus789/g4f:latest
    env_file:
      - .env
    shm_size: '2gb'
    expose:
      - 8080
      - 1337
      - 7900
    ports:
      - 8080:8080
      - 1337:1337
      - 7900:7900

volumes:
  pg-data:
