version: "3"

services:
  bot:
    build: .
    image: discord/bot:latest
    container_name: bot
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - internal

networks:
  internal: {}
